### ISSUE TITLE
User access removed, access is now via a team

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/rack-redirect#4]
Hi there 

 This user had Direct Member access to this repository and access via a team. 

 Access is now only via a team. 

 If you have any questions, please post in #ask-operations-engineering on Slack. 

 This issue can be closed.

**Comment by zheileman** [comment]
@AntonyBishop I've lost my admin permissions in this repo. The family-team only has read access. Can you please reinstate access, either to my user or to the team? Thank you.

**Comment by zheileman** [comment]
@AntonyBishop I've lost my admin permissions in this repo. The family-team only has read access. Can you please reinstate access, either to my user or to the team? Thank you.

**Comment by AntonyBishop** [comment]
Hi @zheileman . I have given admin permissions to the Team.
